#!/bin/bash
echo "========================================"
echo "Product Importer - Starting Services"
echo "========================================"
echo ""
echo "Please run these commands in separate terminals:"
echo ""
echo "Terminal 1 - Redis:"
echo "  redis-server"
echo ""
echo "Terminal 2 - Celery Worker:"
echo "  celery -A celery_app worker --loglevel=info"
echo ""
echo "Terminal 3 - Flask UI:"
echo "  python flask_app.py"
echo ""
echo "Terminal 4 - FastAPI API:"
echo "  python api.py"
echo ""
echo "========================================"

